### ISSUE TITLE
Does not work on Node 14

### ISSUE THREAD

**Issue by msipinski** [ibmruntimes/chcp#11]
Hi, this package does not work on Node 14 - current LTS, because of changes in the API. Changing below lines fixes it:

https://github.com/ibmruntimes/chcp/blob/8baae869489d22cb6947deffb74757e3bdbbeaab/src/chcp.cc#L42
```cpp
        String::NewFromUtf8(isolate, "argument should be a number.").ToLocalChecked()));
```

https://github.com/ibmruntimes/chcp/blob/8baae869489d22cb6947deffb74757e3bdbbeaab/src/chcp.cc#L45
```cpp
  chcp = args[0].As<Int32>()->Value();
```

**Comment by gireeshpunathil** [comment]
@msipinski - thanks for reporting this. I don't have a windows system with me right now to check; but feel free to come up with a PR if you wish!

**Comment by msipinski** [comment]
I'll make the PR with my changes later. I was worried about backwards compatibility so I checked if it builds for different target versions. I took some versions listed on https://node.green/ and prepared simple `cmd` script with lines like:
```cmd
cmd /c npx node-gyp rebuild --target=v14.17.6 > log/14.17.6.txt 2>&1 && echo 14.17.6: pass || echo 14.17.6: fail
```
The result was:
```
16.9.1: pass
16.8.0: pass
16.5.0: pass
16.3.0: pass
16.0.0: pass
15.14.0: pass
14.17.6: pass
14.5.0: pass
13.14.0: pass
13.1.0: pass
12.10.0: fail
12.8.1: fail
12.4.0: fail
11.15.0: fail
10.24.1: fail
10.8.0: fail
10.3.0: fail
9.11.2: fail
8.9.4: fail
8.6.0: fail
8.2.1: fail
7.10.1: fail
7.5.0: fail
6.17.1: fail
6.4.0: fail
5.12.0: fail
4.9.1: fail
0.12.18: fail
0.10.48: fail
```
and
```
13.0.0: pass
```
Should I also change value of `engines.node` inside `package.json`? Should it be `">= 13.0.0"`?

If you want I can also attach the logs the script saved for each version.

**Comment by gireeshpunathil** [comment]
> Should it be ">= 13.0.0"?

Yes. given that v12 is out of [active maintenance](https://nodejs.org/en/about/releases/), I think this will do; that is, we can limit our support to v13 and above.

thanks for doing this!

**Comment by richardlau** [comment]
Wouldn't it be better to use nan or n-api instead of directly calling the V8 API's?

**Comment by gireeshpunathil** [comment]
thanks @richardlau for that suggestion. I used neither of it, though have a rough idea about its stability in these situations. @msipinski - want to try that route?

**Comment by msipinski** [comment]
Ok, I have never used it before but by using `napi.h` from `node-addon-api@1.7.2`  npm package I managed to go down to `node@8.6.0` inclusive and also version 6.17.1 (which is a weird exception).

I used this official example as a guide:
https://github.com/nodejs/node-addon-examples/tree/HEAD/2_function_arguments/node-addon-api

I also bumped some packages.

PR has just been created
