### ISSUE TITLE
unable to install, wrong os

### ISSUE THREAD

**Issue by Eskibear** [ibmruntimes/chcp#8]
Step to reproduce:
`npm i chcp`

Error log:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for chcp@1.0.0: wanted {"os":"windows","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    windows
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by gireeshpunathil** [comment]
hmm... @Eskibear - thanks for reporting this. I am not sure os flavor `win32` is a superset of all windows platforms or not, will get back on this.

**Comment by HarshithaKP** [comment]
@Eskibear We fixed this by changing generic os dependency to `win32` in version 1.1.0 , can you please check and revert.

**Comment by Eskibear** [comment]
It works for me now. Thanks.
